apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-mon-app
  labels:
    app: traffic-mon
    tier: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: middleware
  template:
    metadata:
      labels:
        app: traffic-mon
        tier: middleware
    spec:
      containers:
        - name: traffic-mon
          image: "pi4apps:5000/traffic-mon:2.0.3"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1500m" # 1.5 CPU
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 3
            initialDelaySeconds: 60
